FROM ubuntu:20.04


RUN apt-get update          \
    && apt-get install -y   \
    nginx                   \
    sqlite3                 \
    openssl                 \
    php-fpm                 \
    php-mysql               \
    php-mbstring            \    
    php-common              \
    php-bcmath              \ 
    php-json                \    
    php-xml                 \
    php-zip                                                      

#
# When added to the first run command it opens up a tzconfig question
# and will not finish installation. have this on separate RUN instead
# Also this seems to resolve the openssl issue, 
# occurs when line below is removed
#
RUN apt-get install -y git

COPY docker/nginx.conf /etc/nginx/nginx.conf
COPY docker/php.ini /etc/php/7.4/fpm/php.ini
COPY docker/default /etc/nginx/sites-available/default

WORKDIR /var/www/html

CMD service php7.4-fpm start    \
    && nginx -g 'daemon off;'   \
    && bash
